---
- name: Create symlink from source to destination
  ansible.builtin.file:
    src: "{{ role_path}}/files/{{ item.filename }}"
    dest: "{{ item.path }}/{{ item.filename }}"
    state: link
    force: yes
  loop: "{{ dotfiles_configs }}"
