---
- name: Ensure the directory exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ dotfiles_configs }}"

- name: Create symlink from source to destination
  ansible.builtin.file:
    src: "{{ role_path}}/files/{{ item.filename }}"
    dest: "{{ item.path }}/{{ item.filename }}"
    state: link
    force: yes
  loop: "{{ dotfiles_configs }}"
