---
- name: Ensure the dotfiles directories exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/dotfiles/{{ item.package }}"
    state: directory
    mode: '0755'
  loop: "{{ dotfiles_configs }}"

- name: Copy dotfiles to their respective directories
  ansible.builtin.copy:
    src: "{{ item.filename }}"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles/{{ item.package }}/{{ item.filename }}"
    mode: '0644'
  loop: "{{ dotfiles_configs }}"

- name: Install GNU Stow
  ansible.builtin.package:
    name: stow
    state: present
  when: ansible_facts.pkg_mgr == 'homebrew' or ansible_facts.pkg_mgr == 'apt'

- name: Run Stow for each package
  ansible.builtin.command:
    cmd: "cd {{ lookup('env', 'HOME') }}/dotfiles && stow {{ item.package }}"
  loop: "{{ dotfiles_configs }}"
