---
- name: Ensure the dotfiles directories exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/dotfiles/{{ item.package }}"
    state: directory
    mode: '0755'
  loop: "{{ dotfiles_configs }}"

- name: Copy dotfiles to their respective directories
  ansible.builtin.copy:
    src: "{{ item.filename }}"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles/{{ item.package }}/{{ item.filename }}"
    mode: '0644'
  loop: "{{ dotfiles_configs }}"

- name: Run Stow for each package
  command: >
    cd {{ lookup('env', 'HOME') }}/dotfiles && stow {{ item.package }} -v
  loop: "{{ dotfiles_configs }}"
