dotfiles:
  - src: init.lua
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim/init.lua"
  - src: config.lua
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim/lua/config.lua"
  - src: vim_pack.lua
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim/lua/config/vim_pack.lua"
