---
- name: Check if Packer is already installed
  ansible.builtin.stat:
    path: "{{ packer_dest }}"
  register: packer_stat

- name: Clone Packer repository
  ansible.builtin.git:
    repo: "{{ packer_repo }}"
    dest: "{{ packer_dest }}"
    depth: 1
    update: no
  when: not packer_stat.stat.exists
