---
# Install neovim and configure it

- name: Include Darwin tasks
  ansible.builtin.include_tasks: darwin.yaml
  when: ansible_facts['os_family'] == "Darwin"

- name: Include RedHat tasks
  ansible.builtin.include_tasks: redhat.yaml
  when: ansible_facts['os_family'] == "RedHat"

# Symlink neovim dotfiles
- name: Symlink neovim dotfiles
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/common/tasks/symlink_dotfiles.yaml"

- name: Remove obsolete Packer installation
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    state: absent
